"""
Confidence scoring and transparency labels for Provenance Guard.

Design decision (see planning.md "Uncertainty representation"):
A false positive -- telling a human creator their work was flagged as
AI-generated -- is worse than a false negative on a creative-writing platform.
So the threshold for "likely_ai" is set deliberately HIGH (0.70) while the
threshold for "likely_human" is comparatively lower (0.30). It is easier to
end up "uncertain" than to end up confidently accused.
"""

LLM_WEIGHT = 0.75
STYLOMETRIC_WEIGHT = 0.25

THRESHOLD_AI = 0.70
THRESHOLD_HUMAN = 0.30


def combine_scores(llm_score: float, stylometric_score: float) -> float:
    """Weighted average of the two signals. LLM signal weighted substantially
    higher (0.75) because calibration testing (see planning.md) showed the
    stylometric signal is unreliable on short text -- TTR is inflated and
    sentence-count is too low for variance to mean much under ~100 words.
    The stylometric signal still contributes 0.25 so it can pull the score
    when it strongly disagrees, but it doesn't dominate."""
    return round(LLM_WEIGHT * llm_score + STYLOMETRIC_WEIGHT * stylometric_score, 4)


def classify(combined_score: float) -> str:
    if combined_score >= THRESHOLD_AI:
        return "likely_ai"
    if combined_score <= THRESHOLD_HUMAN:
        return "likely_human"
    return "uncertain"


def confidence_from_combined(combined_score: float) -> float:
    """Maps the 0-1 combined score to a 0-1 'confidence' that represents
    distance from the uncertain midpoint (0.5), not raw AI-likelihood.
    A combined score of 0.95 -> confidence 0.90 (very confident AI).
    A combined score of 0.55 -> confidence 0.10 (barely confident either way).
    A combined score of 0.50 -> confidence 0.0 (totally uncertain)."""
    return round(abs(combined_score - 0.5) * 2, 4)


# ---------------------------------------------------------------------------
# Transparency label variants -- verbatim text shown to end users.
# These three strings ARE the required deliverable; do not just summarize
# them, the exact text matters.
# ---------------------------------------------------------------------------

LABEL_LIKELY_AI = (
    "This content has been flagged as likely AI-generated by our automated "
    "detection system (confidence: {confidence_pct}%). This is an automated "
    "assessment and may be incorrect. If you wrote this yourself, you can "
    "appeal this classification."
)

LABEL_LIKELY_HUMAN = (
    "Our system found no strong signals of AI generation in this content "
    "(confidence: {confidence_pct}%). This reflects an automated assessment, "
    "not a verified guarantee of authorship."
)

LABEL_UNCERTAIN = (
    "Our system could not confidently determine whether this content is "
    "AI-generated or human-written (confidence: {confidence_pct}%). Treat "
    "this classification as inconclusive."
)

_LABEL_TEMPLATES = {
    "likely_ai": LABEL_LIKELY_AI,
    "likely_human": LABEL_LIKELY_HUMAN,
    "uncertain": LABEL_UNCERTAIN,
}


def generate_label(attribution: str, confidence: float) -> str:
    template = _LABEL_TEMPLATES[attribution]
    return template.format(confidence_pct=round(confidence * 100))


def score_text(llm_score: float, stylometric_score: float) -> dict:
    """Full pipeline from two raw signal scores to attribution + label."""
    combined = combine_scores(llm_score, stylometric_score)
    attribution = classify(combined)
    confidence = confidence_from_combined(combined)
    label = generate_label(attribution, confidence)
    return {
        "combined_score": combined,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    }
